"""
Extend reading passages to 700-900 words (real IELTS length)
"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from sqlalchemy.orm import Session
from services.db import SessionLocal
from services.models import IeltsReading

def extend_passages(db: Session):
    """Extend reading passages to proper IELTS length"""
    print("Extending reading passages...")
    
    # Extend "The History of Tea"
    tea_passage = db.query(IeltsReading).filter(IeltsReading.title == "The History of Tea").first()
    if tea_passage:
        tea_passage.passage_text = """The story of tea begins in China. According to legend, in 2737 BC, the Chinese emperor Shen Nung was sitting beneath a tree while his servant boiled drinking water, when some leaves from the tree blew into the water. Shen Nung, a renowned herbalist, decided to try the infusion that his servant had accidentally created. The resulting drink was what we now call tea. While this legend may be apocryphal, archaeological evidence suggests that tea was indeed consumed in China as early as the Shang dynasty (1600-1046 BC), where it was used primarily for medicinal purposes.

Tea containers have been found in tombs dating from the Han dynasty (206 BC – 220 AD) but it was under the Tang dynasty (618–906 AD), that tea became firmly established as the national drink of China. It became such a favourite that during the late eighth century a writer called Lu Yu wrote the first book entirely about tea, the Ch'a Ching, or Tea Classic. This comprehensive work described the cultivation, preparation, and consumption of tea in great detail, establishing standards that would influence tea culture for centuries. Lu Yu's work covered everything from the proper way to grow tea plants to the specific vessels and utensils that should be used in tea preparation. It was shortly after this that tea was first introduced to Japan, by Japanese Buddhist monks who had travelled to China to study. These monks brought tea seeds and the knowledge of tea preparation back to their monasteries, where it became an integral part of meditation practices, helping monks stay alert during long sessions of meditation.

The spread of tea beyond Asia was slow but steady. In the 16th century, Portuguese traders and missionaries encountered tea in China and brought it to Europe. However, it was the Dutch who established the first regular tea trade with China in the early 17th century, making tea available to the European upper classes. Tea reached England in the 1650s, initially sold as a medicinal herb in coffee houses. By the 18th century, tea had become Britain's most popular beverage, leading to the establishment of extensive tea plantations in India and Ceylon (now Sri Lanka) to meet the growing demand. The British East India Company played a crucial role in this expansion, developing tea estates in Assam and Darjeeling, regions that would become famous for their distinctive tea varieties.

Tea drinking has become a ritual in many cultures. In the United Kingdom, for example, tea is consumed daily by the majority of the population. The British tradition of afternoon tea began in the 1840s when Anna, the Duchess of Bedford, started inviting friends for tea and cake in the afternoon. This practice quickly spread among the upper classes and eventually became a national custom. In China, the traditional tea ceremony, known as Gongfu Cha, emphasizes the aesthetic and spiritual aspects of tea preparation, with each step performed with deliberate care and attention. The Japanese tea ceremony, or Chanoyu, is perhaps the most elaborate tea ritual in the world, incorporating principles of harmony, respect, purity, and tranquility. These ceremonies can last for hours and require years of practice to master.

Today, tea is the second most consumed beverage in the world, after water. It is grown in many countries including China, India, Kenya, and Sri Lanka. Different cultures have developed their own unique ways of preparing and serving tea, from the elaborate Japanese tea ceremony to the simple British cup with milk and sugar. In Morocco, mint tea is a symbol of hospitality and is served throughout the day. In Turkey, tea is served in small tulip-shaped glasses and is consumed in large quantities. In Russia, tea is traditionally served with lemon and sugar, often accompanied by jam or honey. Scientific research has also confirmed many of the health benefits traditionally associated with tea consumption, including its antioxidant properties and potential cardiovascular benefits. Studies have shown that regular tea consumption may reduce the risk of heart disease, stroke, and certain types of cancer. The global tea industry continues to evolve, with new varieties and blends constantly being developed to meet changing consumer preferences. From traditional black and green teas to herbal infusions and bubble tea, the world of tea continues to expand and innovate."""
        tea_passage.word_count = len(tea_passage.passage_text.split())
        print(f"  Extended 'The History of Tea' to {tea_passage.word_count} words")
    
    # Extend "The Impact of Urbanization on Wildlife"
    urban_passage = db.query(IeltsReading).filter(IeltsReading.title == "The Impact of Urbanization on Wildlife").first()
    if urban_passage:
        urban_passage.passage_text = """As human populations continue to grow and cities expand, the natural habitats of many species are being fragmented or destroyed. This process, known as urbanization, has significant impacts on wildlife populations around the world. The United Nations projects that by 2050, 68% of the world's population will live in urban areas, up from 55% today. This unprecedented urban growth poses serious challenges for biodiversity conservation. The rate of urban expansion is particularly rapid in developing countries, where cities are growing at rates of 3-5% annually, far outpacing population growth.

One of the most immediate effects of urbanization is habitat loss. When forests, grasslands, and wetlands are converted into residential and commercial areas, the plants and animals that depend on these ecosystems lose their homes. This habitat fragmentation creates isolated patches of natural habitat that may be too small to support viable populations of certain species. Large mammals, in particular, require extensive territories and are often the first to disappear from urbanizing landscapes. Species such as tigers, elephants, and wolves have seen their ranges dramatically reduced as human settlements expand. Some species are able to adapt to urban environments, while others are pushed to the brink of extinction. The edge effects created by habitat fragmentation can extend hundreds of meters into remaining habitat patches, further reducing their suitability for sensitive species.

Pollution is another major consequence of urbanization. Air pollution from vehicles and industry can harm wildlife directly, causing respiratory problems and other health issues. Birds living in urban areas often show higher levels of heavy metals in their tissues compared to their rural counterparts. Water pollution from runoff can contaminate the water sources that many animals rely on for drinking and reproduction. Urban runoff often contains pesticides, fertilizers, oil, and other chemicals that can be toxic to aquatic life. Light pollution from streetlights and buildings can disrupt the natural behaviors of nocturnal animals, affecting their feeding and breeding patterns. Many bird species have been observed singing earlier in the morning in urban areas due to artificial light, which can affect their mating success. Noise pollution from traffic and construction can interfere with animal communication, making it difficult for species to find mates or warn of predators. Birds in urban areas often sing at higher frequencies to be heard above the urban noise, a phenomenon known as the "urban song dialect."

Despite these challenges, some species have shown remarkable adaptability to urban environments. Birds such as pigeons and sparrows have thrived in cities, taking advantage of the abundant food sources and nesting sites provided by buildings. Similarly, raccoons and foxes have successfully adapted to urban life in many parts of the world. These adaptable species often become synanthropes - animals that live near and benefit from human settlements. However, this urban adaptation is not universal, and many species, particularly those with specialized habitat requirements, cannot survive in urban environments. Specialist species that require specific food sources or habitat conditions are particularly vulnerable to urbanization. The loss of these specialist species can lead to biotic homogenization, where urban areas become dominated by a few generalist species, resulting in reduced overall biodiversity.

Conservationists are now working to create wildlife-friendly urban spaces. This includes creating green corridors that connect fragmented habitats, planting native vegetation in parks and gardens, and reducing light pollution in sensitive areas. Green roofs and vertical gardens are increasingly being incorporated into building designs to provide additional habitat for birds and insects. These efforts aim to allow humans and wildlife to coexist in increasingly urbanized landscapes. Some cities have even implemented wildlife crossing structures such as vegetated overpasses and underpasses to help animals safely navigate roads and highways. These structures have proven particularly effective in reducing wildlife-vehicle collisions and maintaining genetic connectivity between populations.

The concept of "urban ecology" has emerged as an important field of study, recognizing that cities are themselves ecosystems with their own ecological dynamics. Understanding these dynamics is crucial for developing effective strategies to conserve biodiversity in urban areas. This includes studying how urbanization affects species interactions, ecosystem services, and evolutionary processes. Research in urban ecology has revealed that cities can actually support surprising levels of biodiversity, particularly when designed with nature in mind. Urban parks and green spaces can serve as important refuges for wildlife, and even small patches of habitat can support significant numbers of species when properly managed. The challenge for the future is to design cities that accommodate both human needs and wildlife conservation, creating sustainable urban environments that benefit both people and nature."""
        urban_passage.word_count = len(urban_passage.passage_text.split())
        print(f"  Extended 'The Impact of Urbanization on Wildlife' to {urban_passage.word_count} words")
    
    # Extend "The Development of the Bicycle"
    bicycle_passage = db.query(IeltsReading).filter(IeltsReading.title == "The Development of the Bicycle").first()
    if bicycle_passage:
        bicycle_passage.passage_text = """The bicycle has undergone significant changes since its invention in the early 19th century. The first bicycles, known as 'hobby horses' or 'dandy horses', had no pedals and were propelled by the rider pushing their feet against the ground. These early designs, introduced by Baron Karl von Drais in 1817, were essentially wooden frames with two wheels in line and a steering mechanism. While they allowed for faster travel than walking, they were uncomfortable and difficult to ride, particularly on uneven surfaces. Drais's invention was initially called the "Laufmaschine" or "running machine" and was designed as a response to a shortage of horses caused by crop failures and the subsequent need for alternative transportation.

In the 1860s, the velocipede appeared, featuring pedals attached directly to the front wheel. This innovation, often attributed to Pierre Michaux and his son Ernest in Paris, represented a significant advancement in bicycle design. However, the velocipede was still uncomfortable due to its wooden frame and iron tires, which earned it the nickname "boneshaker." The direct drive system also meant that one revolution of the pedals resulted in one revolution of the wheel, limiting the speed that could be achieved. To increase speed, larger front wheels were used, but this made the bicycle more dangerous and difficult to mount and dismount.

The 1870s saw the introduction of the 'penny-farthing', with its large front wheel and small rear wheel. This design allowed for greater speed because the larger front wheel covered more distance with each pedal revolution. However, the penny-farthing was dangerous due to the rider's high seating position, which made the bicycle prone to tipping forward. Many riders suffered serious injuries from falling off these tall bicycles, and the design was eventually abandoned in favor of safer alternatives. Despite its dangers, the penny-farthing became a symbol of the Victorian era and was featured in numerous photographs and illustrations of the period.

The modern bicycle design emerged in the 1880s with the invention of the 'safety bicycle'. This featured two wheels of equal size and a chain drive to the rear wheel, making it much safer and more comfortable. The safety bicycle was developed independently by several inventors, including John Kemp Starley in England, who introduced the Rover Safety Bicycle in 1885. This design established the basic configuration that bicycles still use today. The pneumatic tire, invented by John Boyd Dunlop in 1888, further improved comfort by providing a cushion against bumps. Dunlop's invention was initially developed for his son's tricycle to make it more comfortable to ride on rough roads. The combination of the safety bicycle design and pneumatic tires made cycling accessible to a much wider audience.

The bicycle played a crucial role in social history, particularly in the emancipation of women. In the late 19th century, the bicycle gave women unprecedented mobility and freedom from traditional gender roles. The "New Woman" of the 1890s was often depicted on a bicycle, symbolizing independence and modernity. Susan B. Anthony, the American women's rights activist, famously said that the bicycle "has done more to emancipate women than anything else in the world." The bicycle also influenced women's fashion, leading to the adoption of more practical clothing such as bloomers, which allowed for greater freedom of movement while cycling.

Today, bicycles continue to evolve with new materials and technologies. Carbon fiber frames make bikes lighter and stronger, while electric motors provide assistance for riders. Electric bicycles, or e-bikes, have seen explosive growth in recent years, particularly in urban areas where they offer a convenient alternative to cars for short trips. Despite these innovations, the basic principle of the bicycle remains unchanged: a simple, efficient machine powered by human energy. The bicycle remains one of the most efficient forms of transportation ever invented, converting approximately 98% of the energy input into forward motion. This efficiency is unmatched by any other form of transportation, including walking, which converts only about 20% of energy into forward motion.

The environmental benefits of cycling have led to increased investment in bicycle infrastructure in cities around the world. Dedicated bike lanes, bike-sharing programs, and other initiatives aim to make cycling safer and more accessible. As concerns about climate change and urban congestion grow, the bicycle is increasingly recognized as part of the solution to sustainable urban transportation. Cities like Amsterdam and Copenhagen have become models of bicycle-friendly urban design, with extensive networks of bike lanes and facilities that make cycling a practical and safe mode of transportation for daily commuters. The bicycle's role in promoting health, reducing pollution, and creating more livable cities ensures that it will remain an important mode of transportation for the foreseeable future."""
        bicycle_passage.word_count = len(bicycle_passage.passage_text.split())
        print(f"  Extended 'The Development of the Bicycle' to {bicycle_passage.word_count} words")
    
    # Extend "The Importance of Sleep"
    sleep_passage = db.query(IeltsReading).filter(IeltsReading.title == "The Importance of Sleep").first()
    if sleep_passage:
        sleep_passage.passage_text = """Sleep is essential for human health and well-being. During sleep, the body repairs tissues, builds muscle, and strengthens the immune system. The brain also processes information and consolidates memories during this time. Lack of sleep can lead to serious health problems including obesity, diabetes, and cardiovascular disease. The Centers for Disease Control and Prevention has declared insufficient sleep a public health epidemic, with approximately one-third of American adults not getting enough sleep on a regular basis. This chronic sleep deprivation has been linked to increased rates of hypertension, heart disease, stroke, and type 2 diabetes.

Adults typically need between 7 and 9 hours of sleep per night, though individual requirements vary. Children and teenagers need more sleep to support their growth and development - infants need up to 16 hours, while teenagers require 8-10 hours. Quality of sleep is just as important as quantity. Deep sleep and REM (rapid eye movement) sleep are particularly important for physical and mental restoration. Deep sleep is when the body repairs tissues and builds muscle, while REM sleep is crucial for memory consolidation and emotional processing. A typical adult goes through four to six sleep cycles per night, each lasting about 90 minutes and including both deep and REM sleep phases. The progression through these sleep stages is essential for feeling rested and refreshed upon waking.

Many factors can affect sleep quality, including stress, diet, exercise, and exposure to light. The blue light emitted by electronic devices can interfere with the production of melatonin, a hormone that regulates sleep. This is because blue light mimics daylight, tricking the brain into thinking it's still daytime and suppressing melatonin production. Experts recommend avoiding screens for at least an hour before bedtime to improve sleep quality. Caffeine and alcohol can also disrupt sleep patterns - caffeine by blocking adenosine receptors and alcohol by fragmenting sleep and reducing REM sleep. Even moderate alcohol consumption can significantly impair sleep quality, particularly in the second half of the night when alcohol is metabolized and the body experiences withdrawal symptoms.

Establishing a regular sleep schedule and creating a comfortable sleep environment can help improve sleep quality. This includes maintaining a consistent bedtime and wake-up time, even on weekends, to regulate the body's internal clock. The bedroom should be cool, dark, and quiet. Some people find white noise machines helpful for masking disruptive sounds. Regular exercise can improve sleep quality, but vigorous exercise should be avoided close to bedtime as it can be stimulating. The timing of meals also affects sleep quality - eating large meals close to bedtime can cause discomfort and indigestion, while going to bed hungry can make it difficult to fall asleep.

Sleep disorders such as insomnia and sleep apnea affect millions of people worldwide. Insomnia, characterized by difficulty falling or staying asleep, can be caused by stress, anxiety, depression, or poor sleep habits. Chronic insomnia can have serious consequences, including impaired cognitive function, mood disturbances, and increased risk of accidents. Sleep apnea, a condition where breathing repeatedly stops and starts during sleep, can lead to chronic fatigue and other health problems if left untreated. These conditions can significantly impact daily functioning and overall health. Treatment options include lifestyle changes, medication, and in some cases, medical devices or surgery. Continuous Positive Airway Pressure (CPAP) machines are commonly used to treat sleep apnea, delivering pressurized air to keep the airway open during sleep.

The economic impact of sleep deprivation is substantial. Studies estimate that insufficient sleep costs the U.S. economy over $400 billion annually in lost productivity. Sleep-deprived workers are more likely to make mistakes, have accidents, and take sick days. The transportation industry has implemented strict regulations on work hours to prevent fatigue-related accidents, recognizing the serious safety risks of sleep deprivation. Some of the world's worst industrial accidents, including the Chernobyl nuclear disaster and the Exxon Valdez oil spill, have been linked in part to sleep-deprived workers making critical errors.

Research continues to uncover new insights into the importance of sleep. Recent studies have found links between poor sleep and increased risk of Alzheimer's disease, as sleep appears to help clear toxic proteins from the brain. The glymphatic system, which was discovered relatively recently, is most active during sleep and helps remove waste products from the brain. Other research has shown that sleep plays a crucial role in emotional regulation and mental health. Sleep deprivation can lead to increased irritability, anxiety, and depression, while adequate sleep helps maintain emotional stability and resilience. As our understanding of sleep grows, so does the recognition that prioritizing sleep is essential for optimal health and performance. The field of sleep medicine continues to expand, with new treatments and interventions being developed to help people achieve better sleep and improve their overall health and well-being."""
        sleep_passage.word_count = len(sleep_passage.passage_text.split())
        print(f"  Extended 'The Importance of Sleep' to {sleep_passage.word_count} words")
    
    db.commit()
    print("✓ All passages extended")

def main():
    db = SessionLocal()
    try:
        extend_passages(db)
        
        # Show final counts
        print("\nFinal passage word counts:")
        readings = db.query(IeltsReading).all()
        for reading in readings:
            print(f"  {reading.title}: {reading.word_count} words")
        
    finally:
        db.close()

if __name__ == "__main__":
    main()
